name: Run My CLI
on:
  workflow_dispatch:

jobs:
  run-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run My CLI Action
        id: run-cli
        uses: revanite-io/pvtr-runner@main # TODO: pin this
        with:
          cli-arguments: "--foo bar --output-format json"
