# see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
# concurrency:
#   group: "${{ github.workflow }}-${{ github.ref }}"
#   cancel-in-progress: true

name: Run Baseline Scanner
on:
  workflow_dispatch:

jobs:
  run-cli:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run My CLI Action
        id: run-cli
        uses: revanite-io/pvtr-runner@main # TODO: pin this
        with:
          REPO_OWNER: privateerproj
          REPO_NAME: privateer
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
