# see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
# concurrency:
#   group: "${{ github.workflow }}-${{ github.ref }}"
#   cancel-in-progress: true

name: Run Baseline Scanner
on:
  workflow_dispatch:

# see https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  # `read` is required for repository access
  contents: read
  # `write` is required to be able to use OIDC workflows
  # id-token: write

jobs:
  run-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run My CLI Action
        id: run-cli
        uses: revanite-io/pvtr-runner@main # TODO: pin this
        with:
          REPO_OWNER: privateerproj
          REPO_NAME: privateer
